// Blog Post Type Definitions / Blog-Beitrags-Typdefinitionen
// Defines TypeScript interfaces for blog post data structures
// Definiert TypeScript-Schnittstellen für Blog-Beitragsdatenstrukturen

import { Author } from "./Author";

// Complete blog post object / Vollständiges Blog-Beitragsobjekt
// Used by: postModel.ts for data operations / Verwendet von: postModel.ts für Datenoperationen
// Used by: All controllers for type safety / Verwendet von: Allen Controllern für Typsicherheit
// Stored in: SQLite database posts table / Gespeichert in: SQLite-Datenbank posts-Tabelle
export interface Post {
  // Unique identifier, auto-incremented / Eindeutige Kennung, auto-inkrementiert
  // Generated by: database / Generiert von: Datenbank
  id: number;

  // Post title displayed in views / Beitragstitel in Ansichten angezeigt
  // Required field / Pflichtfeld
  title: string;

  // URL-friendly version of title / URL-freundliche Version des Titels
  // Example: "My First Post" → "my-first-post" / Beispiel: "My First Post" → "my-first-post"
  // Generated by: postModel.ts createSlug() / Generiert von: postModel.ts createSlug()
  slug: string;

  // Short summary shown in post list / Kurze Zusammenfassung in Beitragsliste angezeigt
  // Required field / Pflichtfeld
  excerpt: string;

  // Full HTML content, sanitized / Vollständiger HTML-Inhalt, bereinigt
  // Sanitized by: postModel.ts using sanitize-html / Bereinigt von: postModel.ts mit sanitize-html
  content: string;

  // Foreign key to authors table / Fremdschlüssel zur authors-Tabelle
  // Can be null if author is deleted / Kann null sein wenn Autor gelöscht wird
  author_id: number | null;

  // Author object (when joined) / Autorenobjekt (wenn verbunden)
  // Optional, populated in queries with JOIN / Optional, gefüllt in Abfragen mit JOIN
  author?: Author;

  // ISO 8601 date string when post was created / ISO 8601 Datumsstring wann Beitrag erstellt wurde
  // Format: "2025-11-09T10:30:00.000Z" / Format: "2025-11-09T10:30:00.000Z"
  createdAt: string;

  // ISO 8601 date string when post was last modified / ISO 8601 Datumsstring wann Beitrag zuletzt geändert wurde
  // Updated by: postModel.ts updatePost() / Aktualisiert von: postModel.ts updatePost()
  updatedAt: string;
}

// Data needed to create a new post / Daten zum Erstellen eines neuen Beitrags
// Used in admin panel "Create Post" form / Verwendet im Admin-Panel "Beitrag erstellen" Formular
// Connects to: admin/posts/edit.njk form / Verbindet zu: admin/posts/edit.njk Formular
export interface CreatePostInput {
  // Post title / Beitragstitel
  title: string;

  // Short summary / Kurze Zusammenfassung
  excerpt: string;

  // Full HTML content / Vollständiger HTML-Inhalt
  content: string;

  // Optional author ID / Optionale Autoren-ID
  author_id?: number | null;
}

// Data needed to update an existing post / Daten zum Aktualisieren eines vorhandenen Beitrags
// Used in admin panel "Edit Post" form / Verwendet im Admin-Panel "Beitrag bearbeiten" Formular
// Connects to: admin/posts/edit.njk form / Verbindet zu: admin/posts/edit.njk Formular
export interface UpdatePostInput {
  // Updated post title / Aktualisierter Beitragstitel
  title: string;

  // Updated excerpt / Aktualisierte Zusammenfassung
  excerpt: string;

  // Updated HTML content / Aktualisierter HTML-Inhalt
  content: string;

  // Updated author ID / Aktualisierte Autoren-ID
  author_id?: number | null;
}
